apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-faucet
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet-faucet
  template:
    metadata:
      labels:
        app: testnet-faucet
    spec:
      initContainers:
      - name: init-rooch
        image: ghcr.io/rooch-network/rooch:v0.8.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /root/.rooch/initialized ]; then
            /rooch/rooch init -m "${INIT_SECRET}" --skip-password
            /rooch/rooch env switch --alias test
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            ls -la /root/.rooch/rooch_config/
            touch /root/.rooch/initialized
          fi
        env:
        - name: INIT_SECRET
          valueFrom:
            secretKeyRef:
              name: rooch-testnet-secrets
              key: init-phrase
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      containers:
      - name: rooch-faucet
        image: ghcr.io/rooch-network/rooch:main
        command: ["/rooch/rooch"]
        args: 
        - "faucet"
        - "server"
        - "--faucet-sender"
        # the first account
        - "rooch19p2jn4laz0lum2wcnnf9pdqztw5jymqw9etltj3awwwtydkuykwsas4mgf"
        - "--faucet-module-address"
        - "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
        - "--faucet-object-id"
        - "0xd5723eda84f691ae2623da79312c7909b1737c5b3866ecc5dbd6aa21718ff15d"
        - "--invitation-object-id"
        - "0x8eea1b91f649d5d8dec6353b0cd1188e5964f05a7a04ff5f8c0e0af77b1cb095"
        - "--discord-token"
        - "$(DISCORD_TOKEN)"
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: rooch-testnet-secrets
              key: discord-token
        ports:
        - containerPort: 6868
        readinessProbe:
          httpGet:
            path: /
            port: 6868
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 6868
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      volumes:
      - name: rooch-data
        persistentVolumeClaim:
          claimName: testnet-faucet-data