[package]
name = "rooch-types"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bech32 = { workspace = true }
bitcoin = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
proptest = { default-features = false, optional = true, workspace = true }
proptest-derive = { default-features = false, optional = true, workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
smt = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
derive_more = { workspace = true }
eyre = { workspace = true }
fastcrypto = { workspace = true }
schemars = {workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
async-trait ={ workspace = true }

starcoin-crypto = { workspace = true, features= ["fuzzing"] }

move-core-types = { workspace = true }

moveos-types = { workspace = true }


[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }

[features]
default = []
fuzzing = [
    "proptest",
    "proptest-derive",
]