[package]
name = "orderbook"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
BitcoinMove = { local = "../../frameworks/bitcoin-move" }

[addresses]
orderbook = "_"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"

[dev-addresses]
orderbook = "0x42"
