[package]
name = "rooch-rpc-api"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
bitcoin = { workspace = true }

move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
move-binary-format = { workspace = true }

moveos-types = { workspace = true }
accumulator = { workspace = true }

rooch-types = { workspace = true }
rooch-open-rpc = { workspace = true }
rooch-open-rpc-macros = { workspace = true }
