[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
wee_alloc = "0.4.5"
wasm-bindgen = "0.2"
minicbor = { version = "0.19.0", features = [] }
heapless = "0.8.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true

[features]
default = ["debug"]
std = []
debug = []