[package]
name = "rooch-da"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
celestia-rpc = { workspace = true }
celestia-types = { workspace = true }

moveos-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
bcs = { workspace = true }
log = { workspace = true }
coerce = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
opendal = { workspace = true }

rooch-config = { workspace = true }
serde_yaml = { workspace = true }
xxhash-rust = { workspace = true, features = ["xxh3"] }
base64 = {workspace = true}
