[package]
name = "publish_modules"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }

[addresses]
rooch_examples =  "_"
std =  "0x1"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
rooch_examples = "0x42"