[package]
name = "pri_generic"
version = "0.0.1"

[dependencies]
# MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/move-stdlib", rev = "main" }
# MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/moveos-stdlib", rev = "main" }
# RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "crates/rooch-framework", rev = "main" }
MoveosStdlib = { local = "../../moveos/moveos-stdlib/moveos-stdlib" }

[addresses]
rooch_examples =  "_"
std =  "0x1"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
rooch_examples = "0x42"
