[package]
name = "rooch-relayer"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
coerce = { workspace = true }
ethers = { workspace = true }
tracing = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
prometheus = { workspace = true }

move-core-types = { workspace = true }

moveos-types = { workspace = true }
moveos-eventbus = { workspace = true }
metrics = { workspace = true }

rooch-types = { workspace = true }
bitcoin-client = { workspace = true }
rooch-config = { workspace = true }
rooch-executor = { workspace = true }
rooch-pipeline-processor = { workspace = true }
rooch-notify = { workspace = true }