[package]
name = "rooch-pruner"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
smt = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

rayon = { workspace = true }

num_cpus = { workspace = true }
parking_lot = { workspace = true }
primitive-types = { workspace = true }

rooch-config = { workspace = true }
rooch-store = { workspace = true }

moveos-common = { workspace = true }
moveos-store = { workspace = true }
moveos-types = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "bench_pruner"
harness = false
