[package]
name = "rooch-rpc-client"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
jsonrpsee = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
hex = { workspace = true }

move-core-types = { workspace = true }

moveos-types = { workspace = true }

rooch-key = { workspace = true }
rooch-types = { workspace = true }
rooch-rpc-api = { workspace = true }
rooch-config = { workspace = true }
