[package]
name = "moveos-verifier"
version = "0.4.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
codespan-reporting = { workspace = true }
termcolor = { workspace = true }
bcs = { workspace = true }
thiserror = { workspace = true }
itertools = { workspace = true }

move-core-types = { workspace = true }
move-model = { workspace = true }
move-binary-format = { workspace = true }
move-package = { workspace = true }
move-compiler = { workspace = true }
move-command-line-common = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
move-symbol-pool = { workspace = true }

moveos-types = { workspace = true }
log = "0.4.21"