[package]
name = "moveos-verifier"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }
codespan-reporting = { workspace = true }
termcolor = { workspace = true }
bcs = { workspace = true }
thiserror = { workspace = true }
itertools = { workspace = true }

move-core-types = { workspace = true }
move-model = { workspace = true }
move-binary-format = { workspace = true }
move-package = { workspace = true }
move-compiler = { workspace = true }
move-command-line-common = { workspace = true }
move-vm-runtime = { workspace = true, features = ["stacktrace", "debugging", "testing"] }
move-vm-types = { workspace = true }
move-symbol-pool = { workspace = true }
move-ir-types = { workspace = true }

moveos-types = { workspace = true }
log = "0.4.21"