[package]
name = "examples/steal_split"
version = "0.0.1"

[dependencies]
RoochFramework = { local = "../../crates/rooch-framework" }

[addresses]
rooch_examples = "_"
moveos_std = "0x2"
rooch_framework =  "0x3"

[dev-addresses]
rooch_examples = "0x42"