[package]
name = "smt"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = { workspace = true }
backtrace = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
byteorder = { workspace = true }
bitcoin_hashes = { workspace = true }
function_name = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
metrics = { workspace = true }
more-asserts = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
primitive-types = { workspace = true }
prometheus = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_bytes = { workspace = true }
thiserror = { workspace = true }
