apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooch-faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooch-faucet
  template:
    metadata:
      labels:
        app: rooch-faucet
    spec:
      initContainers:
      - name: init-rooch
        image: ghcr.io/rooch-network/rooch:v0.7.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /root/.rooch/initialized ]; then
            /rooch/rooch init -m "${INIT_SECRET}" --skip-password
            ls -la /root/.rooch/rooch_config/
            touch /root/.rooch/initialized
          fi
        env:
        - name: INIT_SECRET
          valueFrom:
            secretKeyRef:
              name: rooch-faucet-secrets
              key: init-phrase
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      containers:
      - name: rooch-faucet
        image: ghcr.io/rooch-network/rooch:v0.7.0
        command: ["/rooch-faucet/rooch-faucet"]
        args: 
        - "--discord-token"
        - "$(DISCORD_TOKEN)"
        - "--faucet-grant-amount"
        - "1000000000"
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: rooch-faucet-secrets
              key: discord-token
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      volumes:
      - name: rooch-data
        persistentVolumeClaim:
          claimName: rooch-faucet-data