[package]
name = "RoochExamples"
version = "0.0.1"

[dependencies]
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "moveos/moveos-stdlib/moveos-stdlib", rev = "main" }
#MoveosStdlib = { local = "../../rooch/moveos/moveos-stdlib/moveos-stdlib" }

[addresses]
rooch_examples = "_"

moveos_std = "0x2"
rooch_framework = "0x3"

[dev-addresses]
rooch_examples = "0x42"