[package]
name = "rooch-nursery"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
ciborium = { workspace = true }
wasmer = { workspace = true }
cosmwasm-vm = { workspace = true }
cosmwasm-std = { workspace = true }
once_cell = { workspace = true }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true, features = ["stacktrace", "debugging", "testing"] }
move-vm-types = { workspace = true }


moveos-types = { workspace = true }
moveos-stdlib = { workspace = true }
moveos-wasm = { workspace = true }
moveos-object-runtime = { workspace = true }

rooch-cosmwasm-vm = { workspace = true }
rooch-types = { workspace = true }
rooch-framework = { workspace = true }