name: Deploy Rooch Seed For Match
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name to Checkout'
        required: true
        default: 'latest'
  release:
    types: [ published ]

jobs:
  deploy-rooch-for-match:
    name: deploy rooch seed
    runs-on: self-hosted
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - name: Deploy to GCP TESTNET VM
        env:
          PRIVATE_KEY: ${{ secrets.BTC_MAIN_FULLNODE_PK }}
          HOST: ${{ secrets.BTC_MAIN_FULLNODE }}
          USER: ${{ secrets.BTC_MAIN_FULLNODE_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          sudo apt update
          sudo apt install -y --no-install-recommends openssh-server
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST bash -c "'sleep 30' && docker ps | grep rooch | awk '{print \$1}' | xargs -r docker stop && docker ps -a | grep rooch | awk '{print \$1}' | xargs -r docker rm -f && docker pull 'ghcr.io/rooch-network/rooch:${{ steps.extract-version.outputs.tag-name }}' && docker run -d -v /data:/root -p 50051:50051 'ghcr.io/rooch-network/rooch:${{ steps.extract-version.outputs.tag-name }}' server start -n test --btc-rpc-url '${{secrets.BTC_MAIN_RPC_URL}}' --btc-rpc-username rooch-main --btc-rpc-password '${{secrets.BTC_MAIN_RPC_PWD}}' --btc-network 1 --da '{\"internal-da-server\": {\"servers\": [{\"open-da\": {\"scheme\": \"gcs\", \"config\": {\"bucket\": \"${{secrets.OPENDA_GCP_TESTNET_BUCKET}}\", \"credential\": \"${{secrets.OPENDA_GCP_TESTNET_CREDENTIAL}}\"}}}]}}'"

